# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=12)),
                ('currency_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency_simbol', models.CharField(max_length=12)),
            ],
        ),
    ]
