# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20180228_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(null=True, upload_to='products_images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ProductCardImage',
                'verbose_name_plural': 'ProductCardImages',
            },
        ),
    ]
