# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20180228_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcardimage',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
