# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_productcardimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_product',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
