# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20180307_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='customer_adress',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
