# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_orderdetail_customer_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='shop.Product'),
        ),
    ]
