# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20180309_1321'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.AddField(
            model_name='category',
            name='product_image',
            field=models.ImageField(null=True, upload_to='products_images/'),
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
