# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20180309_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='shop.Product'),
        ),
    ]
