# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20180309_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_adress',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
