# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_order_customer_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_image',
        ),
    ]
