# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_category_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='category_images/'),
        ),
    ]
